version: '3.0'

services:
  custom_django:
    build: .
    command: python ./cowork_space/manage.py runserver 0:8000
    ports:
      - "80:8000"
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./code:/code
